#!/bin/sh

## hyphop ##

HW=

SOC_ID=$(cat /sys/devices/soc0/soc_id)

DEV=eth0

#MOD="meson-gxl realtek mdio-mux-meson-g12a dwmac_meson8b"

MOD="meson-gxl realtek dwmac_meson8b"

case $SOC_ID in
    *GXM*)
    MOD="realtek dwmac_meson8b"
    ;;
    *SM1*)
    ;;
esac

echo "[i] SOC: $SOC_ID load modules $MOD">&2

for i in $MOD; do
    [ -d /sys/module/$i ] || modprobe $i
done

