#!/bin/sh

## hyphop ##

D=$(dirname $0)
DP=$(realpath "$D")
cd $D

MAKE_MT=-j4

DL=../../dl
PREF=../../opt

[ -d "$DL" ] || mkdir -p $DL
[ -d "$PREF" ] || mkdir -p $PREF

PRE2=$(realpath $PREF)
BIN=$PRE2/bin

PATH="$BIN:$PATH"

export PATH=$PATH
