#!/bin/sh

#[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
#[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

logger -t firewall "Reloading Avahi-daemon due to $ACTION of $INTERFACE ($DEVICE)"

/etc/init.d/avahi-daemon restart

