#!/bin/sh

## hyphop ##

# download source again

#[ -d khadas-openwrt ] && \
#    rm -rf khadas-openwrt

#[ -d khadas-openwrt ] || \
#git clone https://github.com/hyphop/khadas-openwrt.git

#cd khadas-openwrt
#git pull

export MAKE_KRESQ_IMAGE=1
export NO_REMOVE_SQUASH=1
export MAKE_ALL=1

../scripts/build sd -e +servers $@

