#!/bin/sh

## hyphop ##

## color test

colors_() {
for x in 0 1 2 3 4 5 6 7 8; do 
    for i in 30 31 32 33 34 35 36 37 ; do 
        for a in 40 41 42 43 44 45 46 47; do 
            echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "
        done
        echo
    done
done
}

colors_
