#!/bin/sh /etc/rc.common

START=93

USE_PROCD=1

PROG=/opt/loops

start_service() {

	procd_open_instance 
	logger -t init.d ""$PROG""
	procd_set_param command "$PROG" --no-daemon
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance

}
