#!/bin/sh /etc/rc.common

## hyphop ##

START=94
USE_PROCD=1

PROG=/opt/mpd_fix

start_service() {

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
}
