#!/bin/sh /etc/rc.common

## hyphop ##

START=94

USE_PROCD=1

PROG=/usr/bin/ympd
PORT=8080

start_service() {

	procd_open_instance 
	logger -t init.d ""$PROG""
	procd_set_param command "$PROG" -w $PORT
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance

}
