#!/bin/sh

## hyphop ##

# download source again

#[ -d khadas-openwrt ] && \
#    rm -rf khadas-openwrt

[ -d khadas-openwrt ] || \
git clone https://github.com/hyphop/khadas-openwrt.git

cd khadas-openwrt
git pull

#exit 0

# prepare new rel

echo REL=19.07.0 > scripts/build.conf.user

# rebuild all for VIM2

./scripts/build -r -1 +servers
./scripts/build  -2 +servers


