#!/bin/sh

## hyphop ##

#= simple console image writer

##
## write compressed images on the fly 
## supported raw | gz | 7z | zip formats
##

for t in /sys/class/block/*/device/model; do
    [ -f $t ] && {
    d=${t#*block/}
    d=${d%%/*}
    egrep -q "Card Reader" $t && {
    SD=/dev/$d
    echo "[i] auto detected dev: $SD ($(cat $t))">&2
    break
    }
    }
done

#IN=
#SD=

for a in "$@"; do
    [ -b "$a" ] && {
	SD="$a"
    }
    [ -f "$a" ] && {
	IN="$a"
    }

done

[ "$SD" ] || {
    echo "[e] target device not defined">&2
    exit 1
}

#echo "[i] burn image to $SD">&2

[ -b $SD ] || {
    echo "[e] not block dev $SD">&2
    exit 1
}

[ "$IN" ] || {
for i in *.gz *.7z *.zip  ; do
    [ -f "$i" ] && {
	IN="$i"
	break
    }
done
}

[ -f $IN ] || {
    echo "[e] not found image $IN">&2
    exit 1
}

echo "[i] IMAGE: $IN > $SD">&2

case "$IN" in
    *.gz)
    echo "[i] gzip image mode">&2

    S=$(gzip -q -l "$IN" | grep ".img")

    [ "$S" ] || {
    echo "[e] broken gzip">&2
    sleep 2
    exit 1
    }

    S=$(echo $S)
    S="${S% *}"
    S="${S% *}"
    S=${S#* }

    [ "$S" ] || {
    echo "[e] broken gzip container">&2
    sleep 2
    exit 1
    }

    echo "[i] write raw image $S bytes to $SD">&2

    echo "# gzip -dc "$IN" | pv -s $S > $SD">&2
    gzip -dc "$IN" | pv -s $S | sudo dd bs=4096 of=$SD
    ;;
    *.xz)
    echo "[i] xz image mode">&2
    xz -dc "$IN" | pv | sudo dd bs=1M of=$SD
    ;;
    *.zip)
    echo "[i] zip image mode">&2
    unzip -l "$IN" "*.img"

    S=$(unzip -l "$IN" "*.img" | head -4 | tail -1 | grep ".img")
    S=$(echo $S)
    S=${S%% *}

    echo "[i] write raw image $S bytes to $SD">&2

    unzip -p "$IN" "*.img" | pv -s $S | sudo dd bs=1M of=$SD

    ;;
    *.7z)
    echo "[i] 7z image mode">&2
    IMG_DATA=$(7z l "$IN" | grep -m1 .img)
    IMG=${IMG_DATA##* }
    IMG_SIZE=${IMG_DATA% *}
    IMG_SIZE=$(echo $IMG_SIZE)
    IMG_SIZE=${IMG_SIZE% *}
    S=${IMG_SIZE##* }
    echo "[i] write $S bytes of $IMG">&2

    7z x "$IN" "$IMG" -so | pv -s $S | sudo dd bs=1M of=$SD

    ;;
    *)
    echo "[i] raw image mode">&2
    sudo dd if="$IN" bs=1M | pv | sudo dd of=$SD
esac

sync
