#!/bin/sh

## hyphop ##

#= opkg wrapper

PR=$(dirname $0)

EXT="$PR/../bin/x86_64"

[ -d "$EXT" ] || {
    echo "[i] opkg not prepared $EXT $0">&2
    echo "[i] use ./build at first !!!">&2
    exit 1
}

export LD_LIBRARY_PATH=$(realpath $EXT/lib)

CACHE=$PR/../bin/opkg-cache

[ -d $CACHE ] || mkdir -p $CACHE

$EXT/lib/libc.so $EXT/bin/opkg --force-space --conf $PR/$0.conf --cache $CACHE $@

