#!/bin/sh

## hyphop ##

PR=$(dirname $0)
opkg=$PR/opkg

echo "[i] install packages">&2

[ -d /tmp/opkg-lists ] || {
    $opkg update
}

#    ppp-mod-pptp \
#    luci-proto-ppp \

# mountd

$opkg install rsync bwm-ng curl procps-ng-pkill tcpdump nano mc \
    fdisk sfdisk i2c-tools usbutils evtest netcat aria2 \
    avahi-daemon-service-ssh avahi-daemon-service-http \
    mount-utils dosfstools e2fsprogs blkid losetup dtc uboot-envtools \
    triggerhappy kmod-hid \
    iw wpad-wolfssl wpa-cli \
    wireless-tools \
    ppp-mod-pptp \
    openvpn-mbedtls luci-app-openvpn \
    iptables-mod-tproxy \
    shadowsocks-libev-ss-redir shadowsocks-libev-ss-local shadowsocks-libev-ss-rules shadowsocks-libev-config luci-app-shadowsocks-libev \
    wpan-tools
