#!/bin/sh

## hyphop ##

#= post install servers variant

PR=$(dirname $0)
opkg=$PR/opkg

NAME=${0#*post_install_}

. $PR/build.conf
. $PR/build.lib

echo "[i] add $NAME">&2

$opkg install openssh-client openssh-sftp-server
$opkg install luci-app-sqm
$opkg install samba36-server luci-app-samba
$opkg install blockd

case $REL in
    18*)
    echo "[i] nfs broken not usable plz use 19.X series">&2
    ;;
    19*)
    $opkg install nfs-kernel-server nfs-kernel-server-utils
    $opkg install mkf2fs f2fs-tools
    ;;
esac

